--SELECT *
--FROM COVID_DEATHS
--ORDER BY 3,4;
--
--SELECT *
--FROM COVID_VACCINATIONS
--ORDER BY 3,4;

--DROP TABLE COVID_VACCINATIONS;

SELECT Location, Dates, total_cases, new_cases, total_deaths, Population
FROM COVID_DEATHS
WHERE CONTINENT IS NOT NULL
ORDER BY 1, 2;



-- Total Cases VS Total Deaths
SELECT Location, dates, total_cases, total_deaths, (total_deaths/total_cases)*100 AS Death_Percentage
FROM COVID_DEATHS
WHERE CONTINENT IS NOT NULL
ORDER BY 1, 2;

-- Total Cases VS Total Deaths in Pakistan
SELECT Location, dates, total_cases, total_deaths, (total_deaths/total_cases)*100 AS Death_Percentage
FROM COVID_DEATHS
WHERE Location like '%Pakistan%' AND CONTINENT IS NOT NULL
ORDER BY dates, Death_Percentage DESC;

-- Total Cases VS Population (Shows what percentage of people got covid)
SELECT Location, dates, total_cases, population, (total_cases/population)*100 AS Cases_Percentage
FROM COVID_DEATHS
WHERE CONTINENT IS NOT NULL
ORDER BY Cases_Percentage DESC;

-- Total Cases VS Population (Shows what percent of people in Pakistan got covid)
SELECT Location, dates, population, total_cases, (total_cases/population)*100 AS Cases_Percentage
FROM COVID_DEATHS
WHERE Location like '%Pakistan%' AND CONTINENT IS NOT NULL
ORDER BY Cases_Percentage DESC;

-- Countries with highest infection rate with respect to population
SELECT LOCATION, POPULATION, MAX(CAST(TOTAL_CASES AS INT)) AS HIGHEST_INFECTION_COUNT, MAX(CAST(TOTAL_CASES AS INT)/CAST(POPULATION AS INT))*100 AS PERCENTAGE_POPULATION_INFECTED
FROM COVID_DEATHS
WHERE CONTINENT IS NOT NULL
GROUP BY LOCATION, POPULATION
ORDER BY PERCENTAGE_POPULATION_INFECTED DESC;

-- Countries with highest death rate with respect to population
SELECT LOCATION, POPULATION, MAX(TOTAL_DEATHS) AS HIGHEST_INFECTION_COUNT, (MAX(TOTAL_DEATHS)/POPULATION) *100 AS PERCENTAGE_POPULATION_DIED
FROM COVID_DEATHS
GROUP BY LOCATION, POPULATION
ORDER BY PERCENTAGE_POPULATION_DIED DESC;

-- Breakdown of Countries with highest death count
SELECT LOCATION, MAX(CAST(TOTAL_DEATHS AS INTEGER)) AS TOTAL_DEATH_COUNT
FROM COVID_DEATHS
WHERE CONTINENT IS NOT NULL
GROUP BY LOCATION
ORDER BY TOTAL_DEATH_COUNT DESC;

-- Breakdown of Continents with highest death count
SELECT CONTINENT, MAX(CAST(TOTAL_DEATHS AS INTEGER)) AS TOTAL_DEATH_COUNT
FROM COVID_DEATHS
WHERE CONTINENT IS NOT NULL
GROUP BY CONTINENT
ORDER BY TOTAL_DEATH_COUNT DESC;

-------      GLOBAL ANALYSIS

-- DEATH RATIO AROUND THE WORLD WITH RESPECT TO DATE
SELECT DATES, SUM(NEW_CASES) AS TOTALCASES, SUM(NEW_DEATHS) AS TOTALDEATHS, (SUM(NEW_DEATHS)/SUM(NEW_CASES)) * 100 AS TOTAL_DEATH_PERCENTAGE
FROM COVID_DEATHS
WHERE CONTINENT IS NOT NULL
GROUP BY DATES
ORDER BY 1, 2;

-- TOTAL DEATH RATIO AROUND THE WORLD
SELECT SUM(NEW_CASES) AS TOTALCASES, SUM(NEW_DEATHS) AS TOTALDEATHS, (SUM(NEW_DEATHS)/SUM(NEW_CASES)) * 100 AS TOTAL_DEATH_PERCENTAGE
FROM COVID_DEATHS
WHERE CONTINENT IS NOT NULL
ORDER BY 1, 2;

-- TOTAL DEATH RATIO AROUND THE WORLD
SELECT SUM(NEW_CASES) AS TOTALCASES, SUM(NEW_DEATHS) AS TOTALDEATHS, (SUM(NEW_DEATHS)/SUM(NEW_CASES)) * 100 AS TOTAL_DEATH_PERCENTAGE
FROM COVID_DEATHS
WHERE CONTINENT IS NOT NULL
ORDER BY 1, 2;


-- lOOKING AT TOTAL POPULATION VS VACCINATIONS
SELECT * FROM COVID_VACCINATIONS;

-- JOIN BOTH TABLES ON LOCATION AND DATES
SELECT * 
FROM COVID_DEATHS DEA
JOIN COVID_VACCINATIONS VAC
ON DEA.LOCATION = VAC.LOCATION
AND DEA.DATES = VAC.DATES;

-- TOTAL POPULATION VS VACCINATIONS
SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATES, DEA.POPULATION, VAC.NEW_VACCINATIONS
FROM COVID_DEATHS DEA
JOIN COVID_VACCINATIONS VAC
ON DEA.LOCATION = VAC.LOCATION
AND DEA.DATES = VAC.DATES
WHERE DEA.CONTINENT IS NOT NULL 
ORDER BY 2, 3;

-- TOTAL POPULATIO VS VACCINATIONS (HOW MUCH POPULATION GOT VACCINATIONS)
SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATES, DEA.POPULATION, VAC.NEW_VACCINATIONS, SUM(CAST(VAC.NEW_VACCINATIONS AS INT)) 
OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATES) AS ACCUMULATED_PEOPLE_VACCINATED
FROM COVID_DEATHS DEA
JOIN COVID_VACCINATIONS VAC
ON DEA.LOCATION = VAC.LOCATION
AND DEA.DATES = VAC.DATES
WHERE DEA.CONTINENT IS NOT NULL 
ORDER BY 2, 3;

------ TOTAL POPULATIO VS VACCINATIONS (HOW MUCH POPULATION GOT VACCINATIONS)

-- USING CTE
WITH PopVSVac(CONTINENT, LOCATION, DATES, POPULATION, NEW_VACCINATIONS, ACCUMULATED_PEOPLE_VACCINATED)
AS (
SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATES, DEA.POPULATION, VAC.NEW_VACCINATIONS, SUM(CAST(VAC.NEW_VACCINATIONS AS INT)) 
OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATES) AS ACCUMULATED_PEOPLE_VACCINATED
FROM COVID_DEATHS DEA
JOIN COVID_VACCINATIONS VAC
ON DEA.LOCATION = VAC.LOCATION
AND DEA.DATES = VAC.DATES
WHERE DEA.CONTINENT IS NOT NULL
)
SELECT PEOPLE_VACCINATED_PERCENTAGE.*, (ACCUMULATED_PEOPLE_VACCINATED/POPULATION)*100 AS VACCINATED_PERCENTAGE
FROM PopVSVac;


-- USING TEMP TABLE
--DROP TABLE PEOPLE_VACCINATED_PERCENTAGE;
CREATE TABLE PEOPLE_VACCINATED_PERCENTAGE
(
Continent VARCHAR2(255),
Location VARCHAR2(255),
dates date,
Population NUMBER(32),
New_Vaccinations VARCHAR2(255),
ACCUMULATED_PEOPLE_VACCINATED NUMBER(32)
);

INSERT INTO PEOPLE_VACCINATED_PERCENTAGE 
SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATES, DEA.POPULATION, VAC.NEW_VACCINATIONS, SUM(CAST(VAC.NEW_VACCINATIONS AS INT)) 
OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATES) AS ACCUMULATED_PEOPLE_VACCINATED
FROM COVID_DEATHS DEA
JOIN COVID_VACCINATIONS VAC
ON DEA.LOCATION = VAC.LOCATION
AND DEA.DATES = VAC.DATES
WHERE DEA.CONTINENT IS NOT NULL;

SELECT PEOPLE_VACCINATED_PERCENTAGE.*, (ACCUMULATED_PEOPLE_VACCINATED/POPULATION)*100 AS VACCINATED_PERCENTAGE
FROM PEOPLE_VACCINATED_PERCENTAGE;

---- Creating View to store data for later visualizations
CREATE VIEW PEOPLE_VACCINATED_PERCENT_VIEW AS
SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATES, DEA.POPULATION, VAC.NEW_VACCINATIONS, SUM(CAST(VAC.NEW_VACCINATIONS AS INT)) 
OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATES) AS ACCUMULATED_PEOPLE_VACCINATED
FROM COVID_DEATHS DEA
JOIN COVID_VACCINATIONS VAC
ON DEA.LOCATION = VAC.LOCATION
AND DEA.DATES = VAC.DATES
WHERE DEA.CONTINENT IS NOT NULL;


